name: dockerbuild
on:
  push:
    branches:
      - 'main'
    paths:
      - 'dockerbuild.Dockerfile'
env:
  IMAGE_NAME: ${{ secrets.REGISTRY }}/ish/dockerbuild

jobs:
  dockerbuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          file: dockerbuild.Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest
