name: nextneopi
on:
  push:
    branches:
      - 'main'
    paths:
      - 'nextneopi/**/*'
env:
  IMAGE_NAME: ${{ secrets.ALI_REGISTRY }}/origyz/nextneopi

jobs:
  nextneopi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ALI_REGISTRY }}
          username: ${{ secrets.ALI_DOCKER_USERNAME }}
          password: ${{ secrets.ALI_DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./nextneopi
          file: ./nextneopi/neopi.Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:neopienv
