name: nodeapp
on:
  push:
    branches:
      - 'main'
    paths:
      - 'nodeapp/**/*'
env:
  IMAGE_NAME: ${{ secrets.REGISTRY }}/ish/nodeapp

jobs:
  basecontainer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./nodeapp
          file: ./nodeapp/base.Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:base
  devcontainer:
    runs-on: ubuntu-latest
    needs: basecontainer
    steps:
      - uses: actions/checkout@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and run Dev Container task
        uses: devcontainers/ci@v0.3
        with:
          context: ./nodeapp
          file: ./nodeapp/dev.Dockerfile
          imageName: ${{ env.IMAGE_NAME }}
          imageTag: dev
          subFolder: nodeapp
          push: always
  deploycontainer:
    runs-on: ubuntu-latest
    needs: basecontainer
    steps:
      - uses: actions/checkout@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and run Dev Container task
        uses: devcontainers/ci@v0.3
        with:
          context: ./nodeapp
          file: ./nodeapp/deploy.Dockerfile
          imageName: ${{ env.IMAGE_NAME }}
          imageTag: train
          subFolder: nodeapp
          push: always
