name: nodeapp
on:
  push:
    branches:
      - 'main'
    paths:
      - 'nodeapp/**/*'
env:
  IMAGE_NAME: ${{ secrets.REGISTRY }}/ish/nodeapp

jobs:
  basecontainer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./nodeapp
          file: ./nodeapp/base.Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:base
  devcontainer:
    runs-on: ubuntu-latest
    needs: basecontainer
    steps:
      - uses: actions/checkout@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./nodeapp
          file: ./nodeapp/dev.Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:dev
  deploycontainer:
    runs-on: ubuntu-latest
    needs: basecontainer
    steps:
      - uses: actions/checkout@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./nodeapp
          file: ./nodeapp/deploy.Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:deploy
