name: package
on:
  push:
    branches:
      - 'main'
    paths:
      - 'package/**/*'
env:
  REGISTRY: swr.cn-east-3.myhuaweicloud.com
  IMAGE_NAME: $REGISTRY/ish/package

jobs:
  pythoncontainer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./package
          file: ./package/python.Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:python
