name: pytorch
on:
  push:
    branches:
      - 'fix-workflows'
    paths:
      - 'pytorch/**/*'
env:
  IMAGE_NAME: ${{ secrets.REGISTRY }}/ish/pytorch

jobs:
  basecontainer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./pytorch
          file: ./pytorch/base.Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:base
  devcontainer:
    runs-on: ubuntu-latest
    needs: basecontainer
    steps:
      - uses: actions/checkout@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and run Dev Container task
        uses: devcontainers/ci@v0.3
        with:
          imageName: ${{ env.IMAGE_NAME }}
          imageTag: dev
          subFolder: pytorch
          noCache: true
          push: always
  traincontainer:
    runs-on: ubuntu-latest
    needs: basecontainer
    steps:
      - uses: actions/checkout@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and run Dev Container task
        uses: devcontainers/ci@v0.3
        with:
          imageName: ${{ env.IMAGE_NAME }}
          imageTag: train
          subFolder: pytorch
          noCache: true
          push: always
