name: r
on:
  push:
    branches:
      - 'main'
    paths:
      - 'r/**/*'
env:
  IMAGE_NAME: ${{ secrets.REGISTRY }}/ish/r

jobs:
  r-base:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./r
          file: ./r/base.Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:base
