name: r
on:
  push:
    branches:
      - 'main'
    paths:
      - 'r/**/*'
env:
  REGISTRY: swr.cn-east-3.myhuaweicloud.com
  IMAGE_NAME: $REGISTRY/ish/r

jobs:
  basecontainer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./r
          file: ./r/base.Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:base
  devcontainer:
    runs-on: ubuntu-latest
    needs: basecontainer
    steps:
      - uses: actions/checkout@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and run Dev Container task
        uses: devcontainers/ci@v0.3
        with:
          context: ./r
          file: ./r/dev.Dockerfile
          imageName: ${{ env.IMAGE_NAME }}
          imageTag: dev
          subFolder: r
          push: always
